export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      style={{ boxSizing: "border-box", margin: "0", padding: "0" }}
    >
      <body>{children}</body>
    </html>
  );
}
