import Header from "../header";
import AboutUs from "../aboutUs";
import Footer from "../footer";
import ServicesDisplay from "./components/servicesDisplay";
import PersonServices from "./components/personServices";
import BuisnessServices from "./components/buisnessServices";
import "./home.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <html style={{ margin: "0px" }}>
      <head>
        <title>Nuevos Servicios</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta charSet="utf-8" />
        <link rel="icon" href="/favicons/favicon.ico" />
      </head>
      <body>
        <Header />
        <ServicesDisplay />
        <AboutUs />
        <PersonServices />
        <BuisnessServices />
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
