import Header from "../header";
import AboutUs from "../aboutUs";
import Footer from "../footer";
import ServicesDisplay from './components/servicesDisplay'
import PersonServices from "../personServices";
import BuisnessServices from "../buisnessServices";
import "./home.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <html>
      <head>
        <title>Nuevos Servicios</title>
      </head>
      <body>
        <Header />
        <ServicesDisplay />
        <PersonServices />
        <BuisnessServices />
        <AboutUs />
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
