import Header from "../header";
import AboutUs from "../aboutUs";
import Footer from "../footer";
import ServicesDisplay from "../main/index";
import PersonServices from "./components/personServices";
import BuisnessServices from "./components/buisnessServices";
import "./home.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <section>
        <Header />
        <ServicesDisplay />
        <AboutUs />
        <PersonServices />
        <BuisnessServices />

        <div>
          <Footer></Footer>
        </div>
      </section>
    </div>
  );
}
